REM INSERTING into APEX_COMP_MAPING
SET DEFINE OFF;
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_STEPS','APEX PAGE','PAGE');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_TEMPLATES','SH. TEMPLATES','TEMPLATE');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_SHORTCUTS','SH. SHORTCUTS','SHORTCUTS');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_ITEMS','SH. APEX ITEMS','APP_ITEM');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_PROCESSING','SH. PROCESING','APP_PROCESS');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_COMPUTATIONS','SH. COMPUTATION','APP_COMPUTATION');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_SECURITY_SCHEMES','SH. AUTHORIZATION SCHEMES','SECURITY_SCHEME');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_PATCHES','SH. BUILD OPT','BUILD_OPTION');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LIST_OF_VALUES_DATA','SH.LIST OF VALUES','LOV');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_PLUGINS','SH. PLUGIN','PLUGIN');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_SHARED_QUERIES','SH. REPORT QUERIES','SHARED_QUERY');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LISTS','SH. LIST','LIST');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LISTS','SH. MENU','MENU');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LISTS','SH. BREADCRUMBS','BREADCRUMB');
COMMIT;