SET DEFINE OFF;
BEGIN
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_STEPS','APEX PAGE','PAGE');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_TEMPLATES','SH. TEMPLATES','TEMPLATE');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_SHORTCUTS','SH. SHORTCUTS','SHORTCUTS');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_ITEMS','SH. APEX ITEMS','APP ITEM');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_PROCESSING','SH. PROCESING','APP PROCESS');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_COMPUTATIONS','SH. COMPUTATION','APP COMPUTATION');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_SECURITY_SCHEMES','SH. AUTHORIZATION SCHEMES','SECURITY SCHEME');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_PATCHES','SH. BUILD OPT','BUILD OPTION');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LISTS_OF_VALUES$','SH.LIST OF VALUES','LOV');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_PLUGINS','SH. PLUGIN','PLUGIN');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_SHARED_QUERIES','SH. REPORT QUERIES','SHARED QUERY');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LISTS','SH. LIST','LIST');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LISTS','SH. MENU','MENU');
Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,DESCRIPTION,COMP_TYPE) values ('WWV_FLOW_LISTS','SH. BREADCRUMBS','BREADCRUMB');
COMMIT;
END;