

drop table bck_version_control_structure;
/

drop table bck_apex_comp_maping;
/

create table bck_version_control_structure as 
 select * from version_control_structure;
/



create table bck_apex_comp_maping as 
 select * from apex_comp_maping;
/

begin
delete from version_control_structure;
delete from apex_comp_maping;
end;
/

begin
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_LIST_TEMPLATES','LIST TEMPLATE','SH. LIST TEMPLATE','LIST_TEMPLATE_NAME','35');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_PAGE_PLUG_TEMPLATES','REGION TEMPLATE','SH. REGION TEMPLATE','PAGE_PLUG_TEMPLATE_NAME','509');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_ROW_TEMPLATES','REPORT TEMPLATE','SH. REPORT TEMPLATE','ROW_TEMPLATE_NAME','511');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_THEMES','THEME','SH. THEMES','THEME_NAME','766');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_BUTTON_TEMPLATES','BUTTON TEMPLATE','SH. BUTTON TEMPLATE','TEMPLATE_NAME','871');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_CAL_TEMPLATES','CALENDAR TEMPLATE','SH. CALENDAR TEMPLATE','NAME','872');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_FIELD_TEMPLATES','LABEL TEMPLATE','SH. LABEL TEMPLATE','TEMPLATE_NAME','873');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_POPUP_LOV_TEMPLATE','POPUP LOV TEMPLATE','SH. POPUP LOV TEMPLATE','PAGE_NAME','874');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_STATIC_FILES','STATIC APP FILE','SH. FILES','FILE_NAME','875');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_COMPANY_STATIC_FILES','STATIC WORKSPACE FILE','SH. STATIC WORKSPACE FILE','FILE_NAME','876');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_REPORT_LAYOUTS','REPORT LAYOUT','SH. REPORT LAYOUT','REPORT_LAYOUT_NAME','877');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_MESSAGES$','MESSAGES','SH. TEXT MESSAGES','NAME','878');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_STEPS','PAGE','APEX PAGE','NAME','17');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_TEMPLATES','PAGE TEMPLATE','SH. PAGE TEMPLATE','NAME','18');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_SHORTCUTS','SHORTCUTS','SH. SHORTCUTS','SHORTCUT_NAME','19');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_ITEMS','APP ITEM','SH. APEX ITEMS','NAME','20');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_PROCESSING','APP PROCESS','SH. PROCESING','PROCESS_NAME','21');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_COMPUTATIONS','APP COMPUTATION','SH. COMPUTATION','COMPUTATION_ITEM','22');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_SECURITY_SCHEMES','SECURITY SCHEME','SH. AUTHORIZATION SCHEMES','NAME','23');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_PATCHES','BUILD OPTION','SH. BUILD OPT','PATCH_NAME','24');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_LISTS_OF_VALUES$','LOV','SH.LIST OF VALUES','LOV_NAME','25');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_PLUGINS','PLUGIN','SH. PLUGIN','NAME','26');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_SHARED_QUERIES','SHARED QUERY','SH. REPORT QUERIES','NAME','27');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_LISTS','LIST','SH. LIST','NAME','28');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_MENUS','BREADCRUMB','SH. BREADCRUMBS','NAME','29');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_AUTHENTICATIONS','AUTH SETUP','SH. AUTH SCHEMES','NAME','32');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_TABS','TAB','SH. TAB','TAB_NAME','33');
  Insert into APEX_COMP_MAPING (APEX_TABLE_NAME,COMP_TYPE,DESCRIPTION,APEX_COL_NAME,ID) values ('WWV_FLOW_ICON_BAR','NAVBAR','SH. CLASSIC NAVBAR ENTRY','ICON_SUBTEXT','34');
end;
/



begin
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('LIST TEMPLATE','/#APEX#/#APP_ID#/templates/list_templates/','467','35',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('REGION TEMPLATE','/#APEX#/#APP_ID#/templates/region_templates/','510','509',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('REPORT TEMPLATE','/#APEX#/#APP_ID#/templates/report_templates/','512','511',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('THEME','/#APEX#/#APP_ID#/themes/','767','766',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('BUTTON TEMPLATE','/#APEX#/#APP_ID#/templates/button_templates/','517','871',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('CALENDAR TEMPLATE','/#APEX#/#APP_ID#/templates/calendar_templates/','518','872',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('LABEL TEMPLATE','/#APEX#/#APP_ID#/templates/label_templates/','519','873',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('POPUP LOV TEMPLATE','/#APEX#/#APP_ID#/templates/pop_lov_templates/','460','874',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('STATIC APP FILE','/#APEX#/#APP_ID#/static_app_files/','768','875',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('STATIC WORKSPACE FILE','/#APEX#/#APP_ID#/static_ws_files/','769','876',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('SHARED QUERY','/#APEX#/#APP_ID#/shared_query/','770','27',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('REPORT LAYOUT','/#APEX#/#APP_ID#/report_layout/','771','877',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('MESSAGES','/#APEX#/#APP_ID#/text_message/','772','878',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('PACKAGE BODY','#SCHEMA#/packages/','61',null,'pkb');
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('PLUGIN','/#APEX#/#APP_ID#/plugins/#NAME#/','62','26',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('APP_ITEMS','/#APEX#/#APP_ID#/app_items/','34','20',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('APP_PROCESS','/#APEX#/#APP_ID#/app_process/','35','21',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('APPLICATION_COMPUTATION','/#APEX#/#APP_ID#/application_computation/','36','22',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('AUTHORIZATION_SCHEME','/#APEX#/#APP_ID#/authorization_scheme/','37','23',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('BREADCRUMBS','/#APEX#/#APP_ID#/breadcrumbs/','39','29',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('LIST_OF_VALUES','/#APEX#/#APP_ID#/list_of_values/','40','25',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('LISTS','/#APEX#/#APP_ID#/lists/','41','28',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('PAGES','/#APEX#/#APP_ID#/pages/','42','17',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('SHORTCUTS','/#APEX#/#APP_ID#/shortcuts/','43','19',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('PAGE TEMPLATE','/#APEX#/#APP_ID#/templates/page_templates/','44','18',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('PACKAGE','#SCHEMA#/packages/','45',null,'pks');
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('PROCEDURE','#SCHEMA#/procedures/','46',null,null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('FUNCTION','#SCHEMA#/functions/','47',null,null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('TYPE','#SCHEMA#/types/','48',null,null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('VIEW','#SCHEMA#/packages/','49',null,null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('MATERIALIZED_VIEW','#SCHEMA#/materialized_views/','50',null,null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('TRIGGER','#SCHEMA#/triggers/','51',null,null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('SCRIPT','#SCHEMA#/scripts/','52',null,null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('BUILD OPTION','/#APEX#/#APP_ID#/build_option/','63','24',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('TAB','/#APEX#/#APP_ID#/tabs/','64','33',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('AUTH SETUP','/#APEX#/#APP_ID#/authentication_schemes/','427','32',null);
Insert into VERSION_CONTROL_STRUCTURE (CODE,PATH,ID,ACMG_ID,FILE_EXT) values ('NAVBAR','/#APEX#/#APP_ID#/navbar/','459','34',null);

commit;
end;
/

